# Generated by Django 4.0.6 on 2022-10-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_cart_id_alter_cartitem_cart'),
        ('carts', '0002_cartitem_variations'),
    ]

    operations = [
    ]
